version: "3"
services: 
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"     
        volumes: 
            - /usr/app/node_modules
            - .:/usr/app
        stdin_open: true 

    test:
        build:
            context: .
            dockerfile: Dockerfile.dev

        volumes: 
            - /usr/app/node_modules
            - .:/usr/app 
        command: ["npm", "run", "test"]
    
    prod:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        stdin_open: true